# Generated by Django 3.1.2 on 2020-10-21 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do plano')),
                ('descricao', models.TextField(blank=True, max_length=100, verbose_name='Descricao do plano')),
                ('valor', models.DecimalField(decimal_places=2, default='0', max_digits=15, verbose_name='Valor')),
                ('desconto_maximo', models.DecimalField(decimal_places=2, default='0', max_digits=15, verbose_name='Desconto máximo %')),
                ('observacoes', models.TextField(blank=True, max_length=250, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'planos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(max_length=50, unique=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='Cnpj')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='Inscrição municipal')),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('site', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('endereco', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('contato_cobranca', models.CharField(blank=True, max_length=30)),
                ('telefone_cobranca', models.CharField(blank=True, max_length=30)),
                ('celular_cobranca', models.CharField(blank=True, max_length=30)),
                ('email_cobranca', models.EmailField(max_length=254, verbose_name='E-mail cobrança')),
                ('cep_cobranca', models.CharField(blank=True, max_length=9)),
                ('endereco_cobranca', models.CharField(blank=True, max_length=40)),
                ('numero_cobranca', models.CharField(blank=True, max_length=10)),
                ('complemento_cobranca', models.CharField(blank=True, max_length=30)),
                ('bairro_cobranca', models.CharField(blank=True, max_length=50)),
                ('cidade_cobranca', models.CharField(blank=True, max_length=50)),
                ('uf_cobranca', models.CharField(blank=True, max_length=2)),
                ('dia_pagamento', models.IntegerField(blank=True, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name='Percentual desconto %')),
                ('forma_pagamento', models.CharField(choices=[('A VISTA', 'A VISTA'), ('PARCELADO', 'PARCELADO'), ('GRATUIDADE', 'GRATUIDADE')], max_length=20, verbose_name='Forma pagamento')),
                ('meio_pagamento', models.CharField(choices=[('BOLETO BANCARIO', 'BOLETO BANCARIO'), ('DINHEIRO EM ESPECIE', 'DINHEIRO EM ESPECIE'), ('DEPOSITO EM CONTA', 'DEPOSITO EM CONTA'), ('CARTAO DE CREDITO', 'CARTAO DE CREDITO'), ('CARTAO DE DEBITO', 'CARTAO DE DEBITO'), ('DEBITO EM CONTA', 'DEBITO EM CONTA'), ('GRATUIDADE', 'GRATUIDADE'), ('OUTROS', 'OUTROS')], max_length=20, verbose_name='Meio de pagamento')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('SUSPENSO', 'SUSPENSO'), ('EXCLUIDO', 'EXCLUIDO'), ('NEGATIVADO', 'NEGATIVADO')], max_length=20, verbose_name='Státus')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, max_length=30, verbose_name='Contrato')),
                ('observacoes', models.TextField(blank=True, max_length=250)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.planos')),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ('nome_fantasia',),
            },
        ),
        migrations.CreateModel(
            name='EmpresaResponsaveis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacoes', models.TextField(blank=True, max_length=250)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresas_responsaveis',
                'ordering': ('empresa',),
            },
        ),
    ]
