# Generated by Django 2.1.4 on 2020-10-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201026_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Nome',
            new_name='nome',
        ),
    ]
